config/routes.rb
Rails.application.routes.draw do

  # customer側ルーティング
  devise_for :customers, controllers: {
   sessions:      'customers/sessions',
   passwords:     'customers/passwords',
   registrations: 'customers/registrations'
  }

  scope module: 'customers' do
    root 'items#top'
    resources :items, only: [:show, :index]
    get 'about' => 'items#about'
   end

  namespace :customers do
   resources :genres, only: [:show]
   patch 'customers/withdraw' => 'customers#withdraw', as: 'customers_withdraw'
   get 'show' => 'customers#show'
   get 'customers/edit' => 'customers#edit'
   patch 'update' => 'customers#update'
   get 'quit' => 'customers#quit'
   get 'orders/about' => 'orders#about', as: 'orders_about'
   get 'orders/complete' => 'orders#complete'
   resources :orders, only: [:create, :new, :index, :show]
   resources :cart_items, only: [:index, :create, :update, :destroy]
   delete 'cart_items' => 'cart_items#all_destroy', as: 'all_destroy'
   resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  # admin側ルーティング
  devise_for :admins, controllers: {
   sessions:      'admins/sessions',
   passwords:     'admins/passwords',
   registrations: 'admins/registrations'
  }

  namespace :admins do
   root :to => 'top#top'
   resources :customers, only: [:index, :edit, :update, :show]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :items, only: [:show, :index, :new, :create, :edit, :update]
   resources :orders, only: [:index, :show, :update]
   resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum order_status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }

end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @search = Customer.ransack(params[:q])
    @customers = @search.result.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admins_customer_path(@customer)
      flash[:notice_update] = "ジャンル情報を更新しました！"
    else
      edit_admins_customer_path(@customer)
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :email, :is_customer_status)
  end
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
	before_action :authenticate_admin!

	def index
		@search = Order.ransack(params[:q])
    @orders = @search.result.page(params[:page]).per(10)
	end

	def show
		@order = Order.find(params[:id])
		@order_details = @order.order_details
	end

	def total(items_total_price)

	end

	def update
		order = Order.find(params[:id])
		order_details = order.order_details
    order.update(order_params)

		if order.order_status == "入金確認"
			order_details.update_all(making_status: "製作待ち")
		end
		redirect_to admins_order_path(order.id)
	end

  private
	def order_params
		params.require(:order).permit(:order_status)
	end


end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
    before_action :authenticate_customer!

    # カート商品一覧を表示
    def index
        @cart_items = current_customer.cart_items
        @total_price = @cart_items.sum{|cart_item|cart_item.item.price_without_tax * cart_item.quantity * 1.1}
        # sumメソッド：合計金額を出す
        # 1行目の@cart_itemsにsumメソッドを用いて{}の||ブロック変数にcart_itemを代入している。(each do || end の文章と同じイメージ)
        # cart_item.item.price_without_tax：アソシエーションしているのでドットでつなげる。
        # 『このcart_itemのitemのprice_without_tax』 → 『このカート商品の商品（単体）の税抜き価格』
        # cart_item.quantity：『このカート商品の個数』
    end

    # カート商品を追加する
    def create
        # @cart_item = current_customer.cart_items.build(item_id: params[:item_id])
        @cart_item = CartItem.new(cart_item_params)
        @cart_item.customer_id = current_customer.id
        @cart_item.item_id = params[:item_id]
        # byebug

        if @cart_item.save
           flash[:notice] = "#{@cart_item.item.name}をカートに追加しました。"
           redirect_to customers_cart_items_path
        else
            flash[:alert] = "個数を選択してください"
            render "customers/items/show"
        end
    end

    # 削除や個数を変更した際、カート商品を再計算する
    def update
        @cart_item = CartItem.find(params[:id])
        #@cart.units += cart_params[:units].to_i
        @cart_item.update(cart_item_params)
        redirect_to customers_cart_items_path
    end

    # カート商品を一つのみ削除
    def destroy
        @cart_item = CartItem.find(params[:id])
        @cart_item.destroy
        flash.now[:alert] = "#{@cart_item.item.name}を削除しました"
        redirect_to customers_cart_items_path
    end

    # カート商品を空ににする
    def all_destroy
        @cart_item = current_customer.cart_items
        @cart_item.destroy_all
        flash[:alert] = "カートの商品を全て削除しました"
        redirect_to customers_cart_items_path
    end

    private

      def cart_item_params
        params.require(:cart_item).permit(:quantity, :item_id, :customer_id)
      end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  before_action :authenticate_customer!

    # マイページへのアクション
    def show
        @customer = current_customer
    end

    # 登録情報編集へのアクション
    def edit
        @customer = current_customer
    end

    # 登録情報の編集を保存するアクション
    def update
        @customer = current_customer
        if @customer.update(customer_params)
           flash[:success] = "登録情報を変更しました。"
           redirect_to customers_show_path
        else
            render 'edit'
        end
    end

    # 登録情報編集画面から退会ページを表示するアクション
    def quit

    end

    # 退会アクション
    def withdraw
        @customer = current_customer
        
        # is_customer_statusカラムにフラグを立てる(default→false(有効状態)をtrue(無効状態)にする）
        @customer.update(is_customer_status: true)
        # ログアウトさせる
        reset_session

        flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
        redirect_to root_path
    end

    private
        def customer_params
            params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :phone_number, :is_customer_status)
        end
end

app/controllers/customers/genres_controller.rb
class Customers::GenresController < ApplicationController
  def show
    @genre = Genre.find(params[:id])
    @items = Item.where(genre_id: @genre.id).page(params[:page]).per(8)
    @genres = Genre.all
  end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController

 def top
  @genres = Genre.all
  @items = Item.all
 end

 def index
  @genres = Genre.all
  @search = Item.ransack(params[:q])
  @items = @search.result.page(params[:page]).per(8)
  @items_all = Item.all
 end

 
 def show
  @item = Item.find(params[:id])
  @cart_item = CartItem.new
  @genres = Genre.all
 end

 def about
    
 end

end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
	before_action :authenticate_customer!

	def about
		@order = Order.new
		@customer = current_customer
		@addresses = ShippingAddress.where(customer_id: current_customer.id)
	end

	def create
		customer = current_customer

		# sessionを使ってデータを一時保存
		session[:order] = Order.new

		cart_items = current_customer.cart_items

		# total_paymentのための計算
		sum = 0
		cart_items.each do |cart_item|
			sum += (cart_item.item.price_without_tax * 1.1).floor * cart_item.quantity
		end

		session[:order][:postage] = 800
		session[:order][:total_payment] = sum + session[:order][:postage]
		session[:order][:order_status] = 0
		session[:order][:customer_id] = current_customer.id
		# ラジオボタンで選択された支払方法のenum番号を渡している
		session[:order][:payment_method] = params[:method].to_i

		# ラジオボタンで選択されたお届け先によって条件分岐
		destination = params[:a_method].to_i

		# ご自身の住所が選択された時
		if destination == 0

			session[:order][:post_code] = customer.postal_code
			session[:order][:address] = customer.address
			session[:order][:name] = customer.last_name + customer.first_name

		# 登録済住所が選択された時
		elsif destination == 1

			address = ShippingAddress.find(params[:shipping_address_for_order])
			session[:order][:post_code] = address.postal_code
			session[:order][:address] = address.address
			session[:order][:name] = address.name 

		# 新しいお届け先が選択された時
		elsif destination == 2

			session[:new_address] = 2
			session[:order][:post_code] = params[:post_code]
			session[:order][:address] = params[:address]
			session[:order][:name] = params[:name]

		end

		# お届け先情報に漏れがあればリダイレクト
		if session[:order][:post_code].presence && session[:order][:address].presence && session[:order][:name].presence
			redirect_to new_customers_order_path
		else
			redirect_to customers_orders_about_path
		end

	end


	def new
		@cart_items = current_customer.cart_items
	end



	def complete
		order = Order.new(session[:order])
		order.save

		if session[:new_address]
			shipping_address = current_customer.shipping_addresses.new
			shipping_address.postal_code = order.post_code
			shipping_address.address = order.address
			shipping_address.name = order.name
			shipping_address.save
			session[:new_address] = nil
		end

		# 以下、order_detail作成
		cart_items = current_customer.cart_items
		cart_items.each do |cart_item|
			order_detail = OrderDetail.new
			order_detail.order_id = order.id
			order_detail.item_id = cart_item.item.id
			order_detail.quantity = cart_item.quantity
			order_detail.making_status = 0
			order_detail.price = (cart_item.item.price_without_tax * 1.1).floor
			order_detail.save
		end

		# 購入後はカート内商品削除
		cart_items.destroy_all
	end

	def index
		@orders = current_customer.orders
	end

	def show
		@order = Order.find(params[:id])
		@order_details = @order.order_details
	end

	# private
		# def shipping_address_params
		# 	params.require(:shipping_address).permit(:customer_id, :postal_code, :name, :address)

	#     def order_params
	#        params.require(:order).permit(:customer_id, :postage, :total_payment, :payment_method, :ordr_status, :post_code, :address, :name)
	#     end


	#     def order_detail_params
	#        params.require(:order_detail).permit(:order_id, :item_id, :quantity, :making_status, :price)
	#     end



end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]


  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/shipping_addresses_controller.rb
class Customers::ShippingAddressesController < ApplicationController

    before_action :authenticate_customer!

    # 配送先一覧/配送先登録画面
    def index
        @shipping_address = ShippingAddress.new
        @shipping_addresses = current_customer.shipping_addresses
    end

    # 配送先登録ボタン
    def create
        @shipping_address = ShippingAddress.new(shipping_address_params)
        @shipping_address.customer_id = current_customer.id
        if @shipping_address.save
            redirect_to customers_shipping_addresses_path
            flash[:success] = "登録しました。"
        else
            @shipping_address = ShippingAddress.new
            @shipping_addresses = current_customer.shipping_addresses
            render 'index'
        end
    end

    # 配送先を削除する
    def destroy
        shipping_address = ShippingAddress.find(params[:id])
        shipping_address.destroy
        redirect_to customers_shipping_addresses_path
    end 

    # 配送先編集ボタン
    def edit
        @shipping_address = ShippingAddress.find(params[:id])
    end

    # 配送先編集保存ボタン
    def update
        shipping_address = ShippingAddress.find(params[:id])
        shipping_address.update(shipping_address_params)
        redirect_to customers_shipping_addresses_path
    end

    private
    def shipping_address_params
        params.require(:shipping_address).permit(:customer_id, :name, :postal_code, :address)
    end

end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/customers/cart_items_helper.rb
module Customers::CartItemsHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/views/customers/orders/about.html.erb
<body>
	<div class="panel panel-warning">
		<div class="panel-heading">
	<h2><span class="label label-default">注文情報入力</span></h2>
	</div>
	<div class="panel-body">

		<%= form_with(url: customers_orders_path, method: :post) do |form| %>
			<h3>支払方法</h3>

			<!-- form.radio_button :カラム名, :保存される値(enumの番号) -->
			<span>　　　</span><%= form.radio_button :method, 0, checked: "checked" %>
	  		<%= form.label :クレジットカード %><br>
	  		<span>　　　</span><%= form.radio_button :method, 1 %>
	  		<%= form.label :銀行振込 %>


			<h3>お届け先</h3>

			<span>　　　</span><%= form.radio_button :a_method, 0, checked: "checked" %>
			<%= form.label :ご自身の住所 %><br>
			<span>　　　　　</span><%= @customer.postal_code %>
			<%= @customer.address %><br>
			<span>　　　　　</span><%= @customer.last_name %>
			<%= @customer.first_name %><br>


			<span>　　　</span><%= form.radio_button :a_method, 1 %>
			<%= form.label :登録済住所から選択 %><br>
			<!-- collection_select(プロパティ名, オブジェクトの配列, value属性の項目, テキストの項目 [, オプション])-->
			<span>　　　　　</span><%= form.collection_select :shipping_address_for_order, @addresses, :id, :shipping_address_for_view %><br>



			<span>　　　</span><%= form.radio_button :a_method, 2 %>
			<%= form.label :新しいお届け先 %><br>
			<div class="form-group col-xs-12">
				<%= form.label :"　　　郵便番号(ハイフンなし)", class: "col-xs-3 control-label"  %>
				<%= form.text_field :post_code, class: "col-xs-4 form-control-static postal_code" %>
			</div>
			<div class="form-group col-xs-12">
				<%= form.label :"　　　住所", class: "col-xs-3 control-label" %>
				<%= form.text_field :address, class: "col-xs-7 form-control-static address" %>
			</div>
			<div class="form-group col-xs-12">
				<%= form.label :"　　　宛名", class: "col-xs-3 control-label" %>
				<%= form.text_field :name, class: "col-xs-4 form-control-static name"%>
			</div>

	   		<%= form.submit "確認画面へ進む", class: 'btn btn-warning col-xs-6 col-xs-offset-1'%>

		<% end %>
	</div>
</body>

app/views/customers/orders/complete.html.erb
<body>
	<div class="thankspage">
		<h1 class="message">ご購入ありがとうございました！</h1>
	</div>
</body>

app/views/customers/orders/index.html.erb
<!--注文履歴一覧 -->
<div class="row">
	<div class="col-xs-12">
		<h3><strong>注文履歴一覧</strong></h3>
		<table class="table table-bordered table-condensed">
		<tr>
			<th>注文日</th>
			<th class="col-xs-3">配送日</th>
			<th class="col-xs-2">注文商品</th>
			<th class="col-xs-1">支払料金</th>
			<th class="col-xs-2">ステータス</th>
			<th class="col-xs-2">注文詳細</th>
		</tr>
		<% @orders.each do |order|%>
		<tr>
			<td class="col-xs-3"><%= order.created_at.strftime('%Y/%m/%d') %></td>
			<td class="col-xs-2"><%= order.post_code %>
				<%= order.address %>
				<%= order.name %>
			</td>
			<td class="col-xs-1">
				<% order.order_details.each do |order_detail| %>
				<%= order_detail.item.name %><br>
			<% end %>
			</td>
			<td class="col-xs-2"><%= order.total_payment.to_s(:delimited, delimiter: ',') %></td>
			<td class="col-xs-2"><%= order.order_status %></td>
			<td><%= link_to "表示する", customers_order_path(order), class: "btn btn-primary" %></td>
		</tr>
		<% end %>
	</table>
	</div>
</div>


app/views/customers/orders/new.html.erb
<div class="row">
    <h3><strong>注文情報確認</strong></h3>
    <div class="col-xs-9">
      <table class="table table-hover table-inverse table-bordered">
        <thead>
          <tr class="info">
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @cart_items.each do |cart_item| %>
            <tr>
              <td class="text-left">
                <%= attachment_image_tag( cart_item.item, :image, size: "60x50", fallback: "no_image.jpg") %>
                <%= cart_item.item.name %>
              </td>
              <td class="text-right">
                ¥<%= ((cart_item.item.price_without_tax * 1.1).floor).to_s(:delimited, delimiter: ',') %>
              </td>
              <td class="text-right">
                  <%= cart_item.quantity %>
              </td>
              <td class="text-right">
                ¥<%= ((cart_item.item.price_without_tax * 1.1).floor * cart_item.quantity).to_s(:delimited, delimiter: ',') %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-xs-3 billing">
      <table class="table table-hover table-condensed table-bordered">
          <tr>
            <th class="info">配送料</th>
            <td class="text-right col-xs-5">
              <!-- sessiomのデータを表示する場合、カラム名に""つける -->
              ¥<%= session[:order]["postage"].to_s(:delimited, delimiter: ',') %>
            </td>
          </tr>
          <tr>
            <th class="info">商品合計</th>
            <td class="text-right">
              ¥<%= (session[:order]["total_payment"] - session[:order]["postage"]).to_s(:delimited, delimiter: ',') %>
            </td>
          </tr>
          <tr>
            <th class="info">請求金額</th>
            <td class="text-right">
              ¥<%= session[:order]["total_payment"].to_s(:delimited, delimiter: ',') %>
            </td>
          </tr>
      </table>
    </div>
    <div class="col-xs-9 billing">
      <table class="table table-hover table-condensed table-bordered">
        <tr>
          <th  class="info">支払方法</th>
          <td class="text-left">
            <%= session[:order]["payment_method"] %>
          </td>
        </tr>
        <tr>
          <th  class="info">お届け先</th>
          <td class="text-left">
            <%= session[:order]["post_code"] %><br>
            <%= session[:order]["address"] %><br>
            <%= session[:order]["name"]  %>
          </td>
        </tr>
      </table>

      <%= link_to "購入を確定する", customers_orders_complete_path, class: 'btn btn-primary col-xs-12' %>

    </div>
</div>

app/views/customers/orders/show.html.erb
<h3><strong>注文履歴詳細</strong></h3>

<div calss="row">
    <div class="col-xs-8">
    	<strong>注文情報</strong>
  	    <table class="table table-bordered table-condensed">
          <tbody>
              <tr>
                <th class="info">注文日</th>
          	    <td class="text-left">
                  <%= @order.created_at.strftime('%Y/%m/%d %H:%M') %>
                </td>
              </tr>
              <tr>
                <th class="info">配送先</th>
                <td class="text-left">
                  <%= @order.post_code %><br>
                  <%= @order.address %><br>
                  <%= @order.name %>
                </td>
              </tr>
              <tr>
                <th class="info">支払方法</th>
                <td class="text-left">
                  <%= @order.payment_method %>
                </td>
              </tr>
              <tr>
                <th class="info">ステータス</th>
                <td class="text-left">
                  <%= @order.order_status %>
                </td>
              </tr>
          </tbody>
        </table>
    </div>

    <div class="col-xs-3 billing">
      <strong>請求情報</strong>
        <table class="table  table-bordered table-condensed">
            <tr>
              <th class="info">配送料</th>
              <td class="col-xs-5">
                ¥<%= @order.postage.to_s(:delimited, delimiter: ',') %>
              </td>
            </tr>
            <tr>
              <th class="info">商品合計</th>
              <td class="col-xs-5">
                ¥<%= (@order.total_payment - @order.postage).to_s(:delimited, delimiter: ',') %>
              </td>
            </tr>
            <tr>
              <th class="info">ご請求金額</th>
              <td class="col-xs-5">
                ¥<%= @order.total_payment.to_s(:delimited, delimiter: ',') %>
              </td>
            </tr>
        </table>
    </div>
    <div class="col-xs-7 order-details">
    	<strong>注文内容</strong>
        <table class="table table-striped table-bordered table-condensed">
          <thead>
            <tr class="info">
                <th>商品</th>
                <th>単価(税込)</th>
                <th>個数</th>
                <th>小計</th>
            </tr>
          </thead>
          <tbody>
        	<% @order_details.each do |order_detail| %>
            <tr>
                <td><%= order_detail.item.name %></td>
                <td>¥<%= (order_detail.item.price_without_tax * 1.1).floor.to_s(:delimited, delimiter: ',') %></td>
                <td><%= order_detail.quantity %></td>
                <td>¥<%= ((order_detail.item.price_without_tax * 1.1).floor * (order_detail.quantity)).to_s(:delimited, delimiter: ',') %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
    </div>
</div>