config/routes.rb
Rails.application.routes.draw do

  # customer側ルーティング
  devise_for :customers, controllers: {
   sessions:      'customers/sessions',
   passwords:     'customers/passwords',
   registrations: 'customers/registrations'
  }

  scope module: 'customers' do
    root 'items#top'
    resources :items, only: [:show, :index]
    get 'about' => 'items#about'
   end

  namespace :customers do
   resources :genres, only: [:show]
   patch 'customers/withdraw' => 'customers#withdraw', as: 'customers_withdraw'
   get 'show' => 'customers#show'
   get 'customers/edit' => 'customers#edit'
   patch 'update' => 'customers#update'
   get 'quit' => 'customers#quit'
   get 'orders/about' => 'orders#about', as: 'orders_about'
   get 'orders/complete' => 'orders#complete'
   resources :orders, only: [:create, :new, :index, :show]
   resources :cart_items, only: [:index, :create, :update, :destroy]
   delete 'cart_items' => 'cart_items#all_destroy', as: 'all_destroy'
   resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  # admin側ルーティング
  devise_for :admins, controllers: {
   sessions:      'admins/sessions',
   passwords:     'admins/passwords',
   registrations: 'admins/registrations'
  }

  namespace :admins do
   root :to => 'top#top'
   resources :customers, only: [:index, :edit, :update, :show]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :items, only: [:show, :index, :new, :create, :edit, :update]
   resources :orders, only: [:index, :show, :update]
   resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy
         has_many :shipping_addresses, dependent: :destroy

    # 退会機能
    def active_for_authentication?
      super && (self.is_customer_status == false)
    end

       validates :last_name,  presence: true
       validates :first_name, presence: true
       validates :last_name_kana,  presence: true
       validates :first_name_kana, presence: true
       validates :phone_number, presence: true
       validates :postal_code,  presence: true
       validates :address, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, {presence: true}
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

  attachment :image
  validates :name, {presence: true}
  validates :description, {presence: true}
  validates :price_without_tax, {presence: true}
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum order_status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

    enum making_status: { "着手不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer

  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def shipping_address_for_view
  	self.postal_code + "　" + self.address + "　" + self.name
  end

end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  before_action :authenticate_admin!,only: [:create,:edit,:update,:index]

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admins_genres_path
    else
      flash[:genre_created_error] = "ジャンル名を入力してください"
    redirect_to
  end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admins_genres_path
      flash[:notice_update] = "ジャンル情報を更新しました！"
    else
      render 'edit'
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name, :is_genres_status)
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!,only: [:create,:edit,:update,:index, :show, :new]

  def show
    @item = Item.find(params[:id])
  end

  def index
    @search = Item.ransack(params[:q])
    @items = @search.result.page(params[:page]).per(10)
  end

  def new
    @items = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admins_item_path(@item)
    else
      flash[:genre_created_error] = "ジャンル名を入力してください"
    redirect_to new_admins_item_path
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_items_path(@item)
      flash[:notice_update] = "ジャンル情報を更新しました！"
    else
      redirect_to edit_admins_item_path(@item)
    end
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :description, :price_without_tax, :image, :is_sales_status)
  end
end

app/controllers/admins/top_controller.rb
class Admins::TopController < ApplicationController
	before_action :authenticate_admin!
  def top
    @orders = Order.where("created_at" === Date.today)
    #whereは与えられた条件にマッチするレコードを全て返す
    #今回は今日来た注文の日をマッチさせている
    #参考URLはこれhttps://easyramble.com/get-today-record-with-rails-activerecord.html
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      case resource
        when Admin
          admins_root_path
        when Customer
          root_path
  		end
	  end





    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number])
    end
end

app/controllers/customers/genres_controller.rb
class Customers::GenresController < ApplicationController
  def show
    @genre = Genre.find(params[:id])
    @items = Item.where(genre_id: @genre.id).page(params[:page]).per(8)
    @genres = Genre.all
  end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/order_details_helper.rb
module Admins::OrderDetailsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins/top_helper.rb
module Admins::TopHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/helpers/customers/genres_helper.rb
module Customers::GenresHelper
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/helpers/customers/orders_helper.rb
module Customers::OrdersHelper
end

app/views/admins/genres/edit.html.erb
<!-- 改行する方法がこれで良いのか -->
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <h2>ジャンル編集</h2><br>

    <div class="edit-genre-form">
    <%= form_for(@genre, url: admins_genre_path) do |f| %>    

          <%= f.label :ジャンル %>
          <%= f.text_field :name,class: "col-md-4" %>

          <%= f.radio_button :is_genres_status, :true %>
          <%= f.label :is_genres_status, "有効"  %>
          <%= f.radio_button :is_genres_status, :false %>
          <%= f.label :is_genres_status, "無効" %>
          <%= f.submit "変更を保存する" ,class: "btn btn-primary" %>
        </div>
    <% end %>
  </div>
</div>

app/views/admins/genres/index.html.erb
<!-- my = 上下のマージン
 5 = 5rem = 80px rem（root em）は相対的なサイズを表す単位。remはルート要素(今回は多分16px?)を基準に相対的なサイズを定める。-->

<!-- 改行する方法がこれで良いのか -->
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">

      <h2>ジャンル追加・一覧画面</h2><br>

    <div class="form-group col-md-10">
    <%= form_for(@genre, url: admins_genres_path) do |f| %>


          <%= f.label :ジャンル %>
          <%= f.text_field :name,class: "col-md-4" %>

          <%= f.radio_button :is_genres_status, :true %>
          <%= f.label :is_genres_status, "有効"  %>
          <%= f.radio_button :is_genres_status, :false %>
          <%= f.label :is_genres_status, "無効" %>
          <%= f.submit "追加" ,class: "btn btn-primary" %>

    <% end %>
    </div>

    <br>
      <!-- ofsetは左右の余白 -->
      <table class="table genre-index">
        <thead>
          <tr>
            <th>ジャンル</th>
            <th>状態</th>
          </tr>
        </thead>

        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td>
                <% if genre.is_genres_status %>
                有効
                <% else %>
                無効
                <% end %>
              </td>
              <td><%= link_to "編集する", edit_admins_genre_path(genre), class: "btn btn-primary" %></td>
            </tr>
            <% end %>
        </tbody>
      </table>
  </div>
</div>