config/routes.rb
Rails.application.routes.draw do

  # customer側ルーティング
  devise_for :customers, controllers: {
   sessions:      'customers/sessions',
   passwords:     'customers/passwords',
   registrations: 'customers/registrations'
  }

  scope module: 'customers' do
    root 'items#top'
    resources :items, only: [:show, :index]
    get 'about' => 'items#about'
   end

  namespace :customers do
   resources :genres, only: [:show]
   patch 'customers/withdraw' => 'customers#withdraw', as: 'customers_withdraw'
   get 'show' => 'customers#show'
   get 'customers/edit' => 'customers#edit'
   patch 'update' => 'customers#update'
   get 'quit' => 'customers#quit'
   get 'orders/about' => 'orders#about', as: 'orders_about'
   get 'orders/complete' => 'orders#complete'
   resources :orders, only: [:create, :new, :index, :show]
   resources :cart_items, only: [:index, :create, :update, :destroy]
   delete 'cart_items' => 'cart_items#all_destroy', as: 'all_destroy'
   resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  # admin側ルーティング
  devise_for :admins, controllers: {
   sessions:      'admins/sessions',
   passwords:     'admins/passwords',
   registrations: 'admins/registrations'
  }

  namespace :admins do
   root :to => 'top#top'
   resources :customers, only: [:index, :edit, :update, :show]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :items, only: [:show, :index, :new, :create, :edit, :update]
   resources :orders, only: [:index, :show, :update]
   resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

  attachment :image
  validates :name, {presence: true}
  validates :description, {presence: true}
  validates :price_without_tax, {presence: true}
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @search = Customer.ransack(params[:q])
    @customers = @search.result.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admins_customer_path(@customer)
      flash[:notice_update] = "ジャンル情報を更新しました！"
    else
      edit_admins_customer_path(@customer)
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :email, :is_customer_status)
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!,only: [:create,:edit,:update,:index, :show, :new]

  def show
    @item = Item.find(params[:id])
  end

  def index
    @search = Item.ransack(params[:q])
    @items = @search.result.page(params[:page]).per(10)
  end

  def new
    @items = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admins_item_path(@item)
    else
      flash[:genre_created_error] = "ジャンル名を入力してください"
    redirect_to new_admins_item_path
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_items_path(@item)
      flash[:notice_update] = "ジャンル情報を更新しました！"
    else
      redirect_to edit_admins_item_path(@item)
    end
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :description, :price_without_tax, :image, :is_sales_status)
  end
end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
    before_action :authenticate_customer!

    # カート商品一覧を表示
    def index
        @cart_items = current_customer.cart_items
        @total_price = @cart_items.sum{|cart_item|cart_item.item.price_without_tax * cart_item.quantity * 1.1}
        # sumメソッド：合計金額を出す
        # 1行目の@cart_itemsにsumメソッドを用いて{}の||ブロック変数にcart_itemを代入している。(each do || end の文章と同じイメージ)
        # cart_item.item.price_without_tax：アソシエーションしているのでドットでつなげる。
        # 『このcart_itemのitemのprice_without_tax』 → 『このカート商品の商品（単体）の税抜き価格』
        # cart_item.quantity：『このカート商品の個数』
    end

    # カート商品を追加する
    def create
        # @cart_item = current_customer.cart_items.build(item_id: params[:item_id])
        @cart_item = CartItem.new(cart_item_params)
        @cart_item.customer_id = current_customer.id
        @cart_item.item_id = params[:item_id]
        # byebug

        if @cart_item.save
           flash[:notice] = "#{@cart_item.item.name}をカートに追加しました。"
           redirect_to customers_cart_items_path
        else
            flash[:alert] = "個数を選択してください"
            render "customers/items/show"
        end
    end

    # 削除や個数を変更した際、カート商品を再計算する
    def update
        @cart_item = CartItem.find(params[:id])
        #@cart.units += cart_params[:units].to_i
        @cart_item.update(cart_item_params)
        redirect_to customers_cart_items_path
    end

    # カート商品を一つのみ削除
    def destroy
        @cart_item = CartItem.find(params[:id])
        @cart_item.destroy
        flash.now[:alert] = "#{@cart_item.item.name}を削除しました"
        redirect_to customers_cart_items_path
    end

    # カート商品を空ににする
    def all_destroy
        @cart_item = current_customer.cart_items
        @cart_item.destroy_all
        flash[:alert] = "カートの商品を全て削除しました"
        redirect_to customers_cart_items_path
    end

    private

      def cart_item_params
        params.require(:cart_item).permit(:quantity, :item_id, :customer_id)
      end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  before_action :authenticate_customer!

    # マイページへのアクション
    def show
        @customer = current_customer
    end

    # 登録情報編集へのアクション
    def edit
        @customer = current_customer
    end

    # 登録情報の編集を保存するアクション
    def update
        @customer = current_customer
        if @customer.update(customer_params)
           flash[:success] = "登録情報を変更しました。"
           redirect_to customers_show_path
        else
            render 'edit'
        end
    end

    # 登録情報編集画面から退会ページを表示するアクション
    def quit

    end

    # 退会アクション
    def withdraw
        @customer = current_customer
        
        # is_customer_statusカラムにフラグを立てる(default→false(有効状態)をtrue(無効状態)にする）
        @customer.update(is_customer_status: true)
        # ログアウトさせる
        reset_session

        flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
        redirect_to root_path
    end

    private
        def customer_params
            params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :phone_number, :is_customer_status)
        end
end

app/controllers/customers/genres_controller.rb
class Customers::GenresController < ApplicationController
  def show
    @genre = Genre.find(params[:id])
    @items = Item.where(genre_id: @genre.id).page(params[:page]).per(8)
    @genres = Genre.all
  end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController

 def top
  @genres = Genre.all
  @items = Item.all
 end

 def index
  @genres = Genre.all
  @search = Item.ransack(params[:q])
  @items = @search.result.page(params[:page]).per(8)
  @items_all = Item.all
 end

 
 def show
  @item = Item.find(params[:id])
  @cart_item = CartItem.new
  @genres = Genre.all
 end

 def about
    
 end

end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
	before_action :authenticate_customer!

	def about
		@order = Order.new
		@customer = current_customer
		@addresses = ShippingAddress.where(customer_id: current_customer.id)
	end

	def create
		customer = current_customer

		# sessionを使ってデータを一時保存
		session[:order] = Order.new

		cart_items = current_customer.cart_items

		# total_paymentのための計算
		sum = 0
		cart_items.each do |cart_item|
			sum += (cart_item.item.price_without_tax * 1.1).floor * cart_item.quantity
		end

		session[:order][:postage] = 800
		session[:order][:total_payment] = sum + session[:order][:postage]
		session[:order][:order_status] = 0
		session[:order][:customer_id] = current_customer.id
		# ラジオボタンで選択された支払方法のenum番号を渡している
		session[:order][:payment_method] = params[:method].to_i

		# ラジオボタンで選択されたお届け先によって条件分岐
		destination = params[:a_method].to_i

		# ご自身の住所が選択された時
		if destination == 0

			session[:order][:post_code] = customer.postal_code
			session[:order][:address] = customer.address
			session[:order][:name] = customer.last_name + customer.first_name

		# 登録済住所が選択された時
		elsif destination == 1

			address = ShippingAddress.find(params[:shipping_address_for_order])
			session[:order][:post_code] = address.postal_code
			session[:order][:address] = address.address
			session[:order][:name] = address.name 

		# 新しいお届け先が選択された時
		elsif destination == 2

			session[:new_address] = 2
			session[:order][:post_code] = params[:post_code]
			session[:order][:address] = params[:address]
			session[:order][:name] = params[:name]

		end

		# お届け先情報に漏れがあればリダイレクト
		if session[:order][:post_code].presence && session[:order][:address].presence && session[:order][:name].presence
			redirect_to new_customers_order_path
		else
			redirect_to customers_orders_about_path
		end

	end


	def new
		@cart_items = current_customer.cart_items
	end



	def complete
		order = Order.new(session[:order])
		order.save

		if session[:new_address]
			shipping_address = current_customer.shipping_addresses.new
			shipping_address.postal_code = order.post_code
			shipping_address.address = order.address
			shipping_address.name = order.name
			shipping_address.save
			session[:new_address] = nil
		end

		# 以下、order_detail作成
		cart_items = current_customer.cart_items
		cart_items.each do |cart_item|
			order_detail = OrderDetail.new
			order_detail.order_id = order.id
			order_detail.item_id = cart_item.item.id
			order_detail.quantity = cart_item.quantity
			order_detail.making_status = 0
			order_detail.price = (cart_item.item.price_without_tax * 1.1).floor
			order_detail.save
		end

		# 購入後はカート内商品削除
		cart_items.destroy_all
	end

	def index
		@orders = current_customer.orders
	end

	def show
		@order = Order.find(params[:id])
		@order_details = @order.order_details
	end

	# private
		# def shipping_address_params
		# 	params.require(:shipping_address).permit(:customer_id, :postal_code, :name, :address)

	#     def order_params
	#        params.require(:order).permit(:customer_id, :postage, :total_payment, :payment_method, :ordr_status, :post_code, :address, :name)
	#     end


	#     def order_detail_params
	#        params.require(:order_detail).permit(:order_id, :item_id, :quantity, :making_status, :price)
	#     end



end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]


  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/shipping_addresses_controller.rb
class Customers::ShippingAddressesController < ApplicationController

    before_action :authenticate_customer!

    # 配送先一覧/配送先登録画面
    def index
        @shipping_address = ShippingAddress.new
        @shipping_addresses = current_customer.shipping_addresses
    end

    # 配送先登録ボタン
    def create
        @shipping_address = ShippingAddress.new(shipping_address_params)
        @shipping_address.customer_id = current_customer.id
        if @shipping_address.save
            redirect_to customers_shipping_addresses_path
            flash[:success] = "登録しました。"
        else
            @shipping_address = ShippingAddress.new
            @shipping_addresses = current_customer.shipping_addresses
            render 'index'
        end
    end

    # 配送先を削除する
    def destroy
        shipping_address = ShippingAddress.find(params[:id])
        shipping_address.destroy
        redirect_to customers_shipping_addresses_path
    end 

    # 配送先編集ボタン
    def edit
        @shipping_address = ShippingAddress.find(params[:id])
    end

    # 配送先編集保存ボタン
    def update
        shipping_address = ShippingAddress.find(params[:id])
        shipping_address.update(shipping_address_params)
        redirect_to customers_shipping_addresses_path
    end

    private
    def shipping_address_params
        params.require(:shipping_address).permit(:customer_id, :name, :postal_code, :address)
    end

end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/customers/cart_items_helper.rb
module Customers::CartItemsHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/views/customers/items/_sidebar.html.erb
    <div class="genrekara" style="font-size :20px;" >
      ジャンルから探す
    </div>

    <table class="table table-bordered table-hover text-center ec-genre-list" >
      <tr>
        <td>
          <%= link_to "全商品を表示", items_path, class:"ec-genre-list-item" %>
        </td>
      </tr>

      <% genres.each do |genre| %>
      <% if genre.is_genres_status == true %>
        <tr>
          <td>
            <%= link_to genre.name, customers_genre_path(genre.id), class:"ec-genre-list-item"%>
            </td>
        </tr>
           <% end %>
           <% end %>
    </table>

app/views/customers/items/about.html.erb
<div class="row">
    <div class="col-xs-6">
     <img src="assets/shef.jpg">
    </div>
    <div class="col-xs-6">
    <div>
        ポワチエ出身。15歳で、ホテル「ルレ・ド・ポワチエ」の見習いシェフとしてキャリアをスタートさせた。その後セーヌ川の船上シェフを務めた。28歳で「コンコルド・ラファエットホテル」の総料理長に就任、1976年にフランスの国家最優秀職人章(Meilleur Ouvrier de France, 略称MOF)の資格を取得。同年来日し、レストラン「ラ・ベル・エポック」で働く。1981年には独立してレストラン「ジャマン」を開店、後に店名を「ジョエル・ロブション」へと改め、現在に至る。ロブションは、レストランガイド「ゴー・ミヨ」に「世紀のシェフ」として紹介された事でも知られている。1990年代以降はフランス国外とりわけ日本での活動が豊富で、日本のフレンチ業界に与えた影響も大きく、日本のメディアでは「フレンチの神様」｢フレンチの皇帝｣と称されることも多い。

        1996年に現役を退くも、その味を愛してやまない人達からの熱烈な声に後押しされる形で2003年に料理人として現役復帰する。

        2020年現在世界10カ国に店舗を持ち、ミシュランガイドにて総数33個の星を獲得しており、「世界一星を持つシェフ」としても知られている。 日本国内では東京に9つの店舗を持ち、そのうちの「ガストロノミー ジョエル・ロブション（恵比寿ガーデンプレイス）」が三つ星、「ラ ターブル ドゥ ジョエル・ロブション（恵比寿ガーデンプレイス）」が二つ星、「ラトリエ ドゥ ジョエル・ロブション（六本木ヒルズ）」が二つ星を獲得している。

        日本国内でのロブション・グループの経営母体は、ピザーラの親会社としても知られる株式会社フォーシーズが受け持っている。 世界的には、東京、香港、マカオ、シンガポールとミシュラン３つ星レストラン４軒の総料理長で、アラン・デュカスの３軒を超え世界最多３つ星シェフであったが、シンガポール店の閉店により、アラン・デュカスと並ぶ３軒の世界最多タイの３つ星シェフとなっていた。

        ドルドーニュ県でレストランを夫婦で経営する娘・ソフィーと、福岡在住の日本女性との息子・ルイ(龍依)・ロブション・安部がいる。ルイは日仏産品の輸出入会社を経営している。
    </div>
    </div>
    <h3><%= link_to "もっと見る", items_path, class: "pull-right", style: "font-family: HiraMinPro-W6; color: #000000; margin: 30px 0;" %></h3>
</div>

app/views/customers/items/index.html.erb
<div class="pull-right" style="margin-bottome: 10px;">
	<%= search_form_for(@search, url:items_path) do |f| %>
		<%= f.label :name, "商品キーワード" %>
		<%= f.search_field :name_cont %>
		<%= f.submit %>
	<% end %>
</div>

<%# 
	以下ransackによる検索機能の説明
	
	search_form_forは、ransack特有の書き方で、form_forのransack版に用意されているもの。
	f.search_field :name_cont もransack特有の書き方
	:name_cont は :検索対象にしたいカラム名_検索方法
	ここでのcontというのはcontains valueの意味で部分一致という意味です。
	他にも
	*_eq 等しい
	*_not_eq 等しくない
	*_lt より小さい
	*_lteq より小さい（等しいものも含む）
	*_gt より大きい
	*_gteq より大きい（等しいものも含む）
 %>

<div class="row">
	<div class="col-xs-2">
		<%= render 'customers/items/sidebar', genres: @genres %>
	</div>

  <h2 style="margin: 20px 0;">商品一覧(全<%= @items_all.count %>件)</h2>
	<div class="col-xs-9 col-xs-offset-1">
		<div class="product-card-content">


		<% @items.each do |item| %>
		<div class="col-xs-3" style="padding-right: 0px; padding-left: 0px; margin: 10px 0;">
			<%= link_to item_path(item.id) ,style: "color: black;", data: {"turbolinks" => false} do %>
				<%= attachment_image_tag item, :image, :fill, 200, 150, format: 'jpeg',fallback: "no_image.jpg" %><br>
				<%= item.name %>
				¥<%= item.price_without_tax.to_s(:delimited, delimiter: ',') %>

			<% end %>
		</div>
		<% end %>
		</div>
	</div>
	<div style="text-align: center;"><%= paginate @items %></div>
</div>

app/views/customers/items/show.html.erb
<div class="row">
	<div class="col-xs-2">
	<%= render 'customers/items/sidebar', genres: @genres %>
	</div>

	<br>
	<div class="col-xs-5">
		<p class="item-content1"><%= attachment_image_tag @item, :image, :fill, 300, 250, format: 'jpeg',fallback: "no_image.jpg", size:'380x300' %></p>
	</div>

	<div class="col-xs-5">
		<%= form_for(@cart_item , url: customers_cart_items_path(item_id: @item), method: :post) do |form| %>
		<h3><%= @item.name %></h3>
		<p><%= @item.description %></p>

	</div>
</div>

<div class="row">
	<div class="col-xs-2">
	</div>
	<div class="col-xs-5">

			<p class="item-content2", style="font-family: arial black">¥ <%= ((@item.price_without_tax*1.1).floor).to_s(:delimited, delimiter: ',') %> (税込)
				<span>　　</span><%= form.select :quantity, [['1個', 1], ['2個', 2], ['3個', 3], ['4個', 4], ['5個', 5], ['6個', 6], ['7個', 7], ['8個', 8], ['9個', 9]], {:prompt => "個数選択"} %></p>
		</div>

		<div class="col-xs-5">
		  <p><%= form.submit "カートに入れる", class:"btn btn-primary" %></p>
		</div>
		<% end %>
	</div>
</div>

app/views/customers/items/top.html.erb
<div class="a" data-turbolinks="false">
    <div class="b"><img class="c" src="assets/cake6.jpg"></div>
    <div class="b"><img class="c" src="assets/cookie1.jpg"></div>
    <div class="b"><img class="c" src="assets/fruites1.jpg"></div>
</div>

<div class="row">
  	<div class="col-xs-2">
    <!-- ジャンルのサイドバーを表示 -->
    <%= render "customers/items/sidebar", genres: @genres %>
    </div>

    <div class="col-xs-9 col-xs-offset-1">
        <h4 style="font-family: HiraMinPro-W6; color: #000000; margin: 20px 0;">ようこそ、NaganoCakeへ！<br>
        このサイトは、ケーキ販売のECサイトになります。<br>
        会員でない方も商品の閲覧はできますが、<br>
        購入には会員登録が必要になります。<br>
        </h4>

        <h3 class="recommended-items" style="font-family: HiraMinPro-W6; color: #000000;">オススメ商品</h3>

        <!-- 商品を4つ表示するようにする -->
        <div class="col-xs-9 col-xs-offset-1">
            <div class="item--card-content">
                <% @items.last(4).each do |item| %>
                    <div class="col-xs-3" style="padding-right: 0px; padding-left: 0px;">
                        <%= link_to item_path(item.id) ,style: "color: black;", data: {"turbolinks" => false} do %>
                            <%= attachment_image_tag item, :image, :fill, 180, 125, format: 'jpeg',fallback: "no_image.jpg" %><br>
                            <%= item.name %><br>
                            ¥<%= item.price_without_tax.to_s(:delimited, delimiter: ',') %>
                        <% end %>
                    </div>
                <% end %>
            <div>
        </div>

        
    </div>
    <h3><%= link_to "もっと見る", items_path, class: "pull-right", style: "font-family: HiraMinPro-W6; color: #000000; margin: 30px 0;" %></h3>
</div>